export const events = [
  {
    name: 'The Architecture of Love',
    imageURL: '/assets/events/EVENT1716123011151.webp',
    price: 350000,
    description:
      'People say that Paris is the city of love, but in some ways, New York deserves the title more. It`s impossible not to fall in love with the city as it`s almost impossible not to fall in love in the city. Raia, a bestselling writer, chose to flee to New York, crashing at her best friend Erin`s apartment, to chase inspirations after years of not being able to write even a single sentence. Raia turned every corner of the city into her "office", walking through the streets of Manhattan, Brooklyn, to Queens, trying to find a story in each person that she encountered, each smile that she saw, each conversation that she overheard, in the eyes of strangers on the street and in the subway. Days, weeks, and months had passed, the fallen leaves of autumn have now been replaced by snowflakes, and all Raia had was a blank screen and misery. ',
    availableSeats: 250,
    maxCapacity: 250,
    limitCheckout: 7,
    startDate: '2024-07-10T15:28:53.412Z',
    endDate: '2024-07-14T13:10:53.412Z',
    userId: 8,
    locationId: 1,
    categoryId: 5,
  },
  {
    name: 'Soundrenaline Festival 2024: Where Music Takes Control',
    imageURL: '/assets/events/EVENT1716123011136.jpeg',
    price: 500000,
    description:
      'Prepare to be immersed in the ultimate music experience at Soundrenaline Festival 2024! Set against the breathtaking backdrop of the Garuda Wisnu Kencana Cultural Park in Bali, this two-day festival is a celebration of music, culture, and the vibrant spirit of Indonesia.',
    availableSeats: 80,
    maxCapacity: 100,
    limitCheckout: 5,
    startDate: '2024-06-30T11:56:53.412Z',
    endDate: '2024-07-03T16:20:53.412Z',
    userId: 4,
    locationId: 1,
    categoryId: 1,
  },
  {
    name: 'EVE: A Night of Art and Innovation Cultura',
    imageURL: '/assets/events/EVENT1716123011129.jpg',
    price: 450000,
    description:
      'Embark on a journey into the future at "EVE: A Night of Art and Innovation," a groundbreaking event bringing together the realms of art, technology, and creativity under one roof. Hosted at the prestigious Innovation Center in the heart of San Francisco, EVE promises to be an evening like no other, where imagination knows no bounds and innovation takes center stage.',
    availableSeats: 120,
    maxCapacity: 200,
    limitCheckout: 8,
    startDate: '2024-06-25T09:42:53.412Z',
    endDate: '2024-06-27T14:05:53.412Z',
    userId: 2,
    locationId: 1,
    categoryId: 2,
  },
  {
    name: 'Arsenal vs Manchester City: Premier League Showdown',
    imageURL: '/assets/events/EVENT1716123011143.webp',
    price: 400000,
    description:
      'Prepare for an electrifying encounter as Arsenal hosts Manchester City in a highly anticipated Premier League showdown at the iconic Emirates Stadium. This clash between two Premier League giants promises thrilling football action, tactical battles, and moments of sheer brilliance from some of the world`s best players.',
    availableSeats: 300,
    maxCapacity: 300,
    limitCheckout: 6,
    startDate: '2024-06-18T08:30:53.412Z',
    endDate: '2024-06-21T12:45:53.412Z',
    userId: 10,
    locationId: 1,
    categoryId: 3,
  },
  {
    name: 'Event Hack-catalyst: Webinar Inspiratif',
    imageURL: '/assets/events/EVENT1716123011158.jpeg',
    price: 35000,
    description:
      'Hackatalyst Dispora Makassar 2024 merupakan salah satu fase dalam rangkaian kompetisi ide produk digital yang diselenggarakan oleh Dinas Pemuda dan Olahraga (Dispora) Kota Makassar. Penyelenggaraan acara ini merupakan wujud dari misi Dispora Kota Makassar untuk melakukan revolusi Sumber Daya Manusia (SDM) dan percepatan digitalisasi yang terjadi di Makassar. Rangkaian acara puncak kompetisi ide ini akan berlangsung dari 20 Mei- 28 Juni 2024. Dalam rangka menyukseskan acara tersebut, Dispora Makassar bersama BINAR Academy menyelenggarakan acara Talkshow untuk meningkatkan kesadaran pemuda Kota Makassar tentang peran pemuda dalam kemajuan kota dan penyelesaian masalah dengan teknologi. Talkshow ini akan dibuka untuk seluruh masyarakat luas (baik yang berdomisili di Makassar ataupun luar domisili Makassar).',
    availableSeats: 150,
    maxCapacity: 250,
    limitCheckout: 7,
    startDate: '2024-06-22T13:20:53.412Z',
    endDate: '2024-06-25T17:40:53.412Z',
    userId: 4,
    locationId: 1,
    categoryId: 4,
  },
  {
    name: 'Komedian Cilik ',
    imageURL: '/assets/events/EVENT1716123011163.png',
    price: 40000,
    description:
      'Hifdzi Khoir salah satu personel grup stand up GJLS tahun 2023 ini akan menggelar tour stand up bertajuk Komedian Cilik di 3 negara yaitu Indonesia, Tokyo dan Singapore serta total ada 12 kota di Indonesia yang akan disambanginya yaitu Purwokerto, Yogyakarta, Solo, Surabaya, Bali, Banyuwangi, Jambi, Bandung, Jakarta, Semarang, Bajarmasin dan Balikpapan.',
    availableSeats: 80,
    maxCapacity: 100,
    limitCheckout: 5,
    startDate: '2024-07-01T19:10:53.412Z',
    endDate: '2024-07-03T22:30:53.412Z',
    userId: 8,
    locationId: 1,
    categoryId: 6,
  },
  {
    name: 'Synchronize Festival 2024: Uniting Music, Art, and Culture',
    imageURL: '/assets/events/EVENT1716123011135.jpeg',
    price: 400000,
    description:
      'Prepare yourself for an extraordinary fusion of music, art, and culture at the Synchronize Festival 2024! Set against the backdrop of the stunning Ancol Beach City in Jakarta, this three-day extravaganza promises to ignite your senses and inspire your soul.',
    availableSeats: 50,
    maxCapacity: 250,
    limitCheckout: 5,
    startDate: '2024-06-20T16:45:53.412Z',
    endDate: '2024-06-22T20:05:53.412Z',
    userId: 8,
    locationId: 158,
    categoryId: 1,
  },
  {
    name: 'Arema FC vs Persebaya Surabaya: The East Java Derby',
    imageURL: '/assets/events/EVENT1716123011142.webp',
    price: 450000,
    description:
      'Prepare for the most thrilling encounter in East Javanese football as Arema FC takes on Persebaya Surabaya in the highly anticipated East Java Derby. This clash between two fierce rivals is not just a game; it`s a battle for regional supremacy, local pride, and the hearts of football fans across East Java.',
    availableSeats: 100,
    maxCapacity: 200,
    limitCheckout: 6,
    startDate: '2024-07-08T14:30:53.412Z',
    endDate: '2024-07-10T18:50:53.412Z',
    userId: 8,
    locationId: 158,
    categoryId: 3,
  },
  {
    name: 'Badarawuhi di Desa Penari',
    imageURL: '/assets/events/EVENT1716123011150.jpeg',
    price: 35000,
    description:
      'A group of students who want to do KKN and meet elders. After living in the village for days, one by one the students experienced unexpected events. Mila, one of the students, experienced terror from Badarawuhi. It turns out that Mila was chosen by the snake demon to be a dancer in his world. Mila`s spirit is trapped in another world, while her body is helpless. This was an unforgettable experience in the village.',
    availableSeats: 70,
    maxCapacity: 100,
    limitCheckout: 4,
    startDate: '2024-07-05T11:10:53.412Z',
    endDate: '2024-07-07T14:30:53.412Z',
    userId: 4,
    locationId: 158,
    categoryId: 5,
  },
  {
    name: 'IU Concert: Love, Poem, Live in Jakarta',
    imageURL: '/assets/events/EVENT1716123011128.jpg',
    price: 400000,
    description:
      'Bergabunglah bersama kami dalam malam yang penuh dengan melodi indah dan emosi yang mendalam di konser eksklusif IU, penyanyi dan penulis lagu berbakat dari Korea Selatan. Konser ini bertajuk Love, Poem, yang merupakan bagian dari tur dunia IU yang sangat dinantikan oleh para penggemar di seluruh dunia.',
    availableSeats: 40,
    maxCapacity: 100,
    limitCheckout: 3,
    startDate: '2024-06-27T09:00:53.412Z',
    endDate: '2024-06-29T12:20:53.412Z',
    userId: 4,
    locationId: 158,
    categoryId: 2,
  },
  {
    name: 'Hackathon 2024',
    imageURL: '/assets/events/EVENT1716123011157.jpg',
    price: 500000,
    description:
      'Hackathon Makassar 2024 merupakan rangkaian kompetisi ide produk digital yang diselenggarakan oleh Dinas Pemuda dan Olahraga (Dispora) Kota Makassar. Penyelenggaraan acara ini merupakan wujud dari misi Dispora Kota Makassar untuk melakukan revolusi Sumber Daya Manusia (SDM) dan percepatan digitalisasi yang terjadi di Makassar. Rangkaian acara puncak kompetisi ide ini akan berlangsung dengan hadian hingga 40 Juta Rupiah.',
    availableSeats: 120,
    maxCapacity: 200,
    limitCheckout: 5,
    startDate: '2024-07-03T13:40:53.412Z',
    endDate: '2024-07-06T17:00:53.412Z',
    userId: 2,
    locationId: 158,
    categoryId: 4,
  },
  //test
  {
    name: 'Pesta Pora 2024: A Celebration of Diversity and Unity',
    imageURL: '/assets/events/EVENT1716123011134.jpeg',
    price: 450000,
    description:
      'Sambutlah keanekaragaman dan persatuan dalam semangat yang meriah di Pesta Pora 2024! Acara tahunan ini mengundang seluruh masyarakat untuk bersatu dalam kegembiraan dan kebersamaan, merayakan perbedaan budaya, tradisi, dan keyakinan dengan penuh semangat.',
    availableSeats: 90,
    maxCapacity: 200,
    limitCheckout: 4,
    startDate: '2024-06-24T14:20:53.412Z',
    endDate: '2024-06-26T17:40:53.412Z',
    userId: 8,
    locationId: 158,
    categoryId: 1,
  },
  {
    name: 'Standup Comedy Tour: IBU - JAKARTA',
    imageURL: '/assets/events/EVENT1716123011162.webp',
    price: 350000,
    description:
      'Setiap manusia akan mengalami titik terendah dalam hidupnya. Praz Teguh pun mengalaminya sekitar tahun 2021 saat sang ibu dipanggil oleh Tuhan.Kesedihan dan rasa kehilangan ini akan disalurkan dalam sebuah pertunjukan komedi. Praz akan menemanimu selama satu jam di setiap kota dan menceritakan betapa dekat dirinya dengan sang Ibu. Banyak momen yang telah berubah. Tur ini hadir di 10 kota di Indonesia dengan komika pembuka, yaitu Aldy Jadong.',
    availableSeats: 60,
    maxCapacity: 100,
    limitCheckout: 4,
    startDate: '2024-07-12T18:30:53.412Z',
    endDate: '2024-07-14T21:50:53.412Z',
    userId: 2,
    locationId: 265,
    categoryId: 6,
  },
  {
    name: 'Persib Bandung vs Persija Jakarta: The Indonesian Derby',
    imageURL: '/assets/events/EVENT1716123011141.jpg',
    price: 450000,
    description:
      'Siapkan diri Anda untuk pertarungan sengit antara dua raksasa sepak bola Indonesia, Persib Bandung dan Persija Jakarta, dalam Derby Indonesia yang legendaris. Pertemuan antara kedua tim ini bukan sekadar pertandingan; ini adalah pertarungan untuk supremasi lokal, kebanggaan suporter, dan kebangkitan semangat sepak bola di seluruh negeri.',
    availableSeats: 80,
    maxCapacity: 100,
    limitCheckout: 5,
    startDate: '2024-07-07T10:15:53.412Z',
    endDate: '2024-07-09T13:35:53.412Z',
    userId: 10,
    locationId: 265,
    categoryId: 3,
  },
  {
    name: 'Sheila On 7 : Karaokean Bareng Duta dan Eros',
    imageURL: '/assets/events/EVENT1716123011127.jpg',
    price: 350000,
    description:
      'Bertepatan dengan resmi beredarnya single terbaru “Film Favorit” dalam bentuk digital pada 29 Januari 2018 lalu, Sheila on 7 meluangkan waktu di Jakarta untuk mempromosikannya. Selama 2 hari yaitu pada tanggal 29 dan 30 Januari 2018, Sheila on 7 mengambil tempat di sebuah kafe kopi di daerah Kemang Jakarta Selatan, untuk menemui media satu per satu seharian penuh.',
    availableSeats: 120,
    maxCapacity: 200,
    limitCheckout: 6,
    startDate: '2024-06-29T17:50:53.412Z',
    endDate: '2024-07-01T21:10:53.412Z',
    userId: 10,
    locationId: 265,
    categoryId: 2,
  },
  {
    name: 'Kung Fu Panda 4',
    imageURL: '/assets/events/EVENT1716123011149.jpg',
    price: 40000,
    description:
      'Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.',
    availableSeats: 100,
    maxCapacity: 150,
    limitCheckout: 5,
    startDate: '2024-06-26T15:40:53.412Z',
    endDate: '2024-06-28T19:00:53.412Z',
    userId: 8,
    locationId: 265,
    categoryId: 5,
  },
  {
    name: 'Wahoo Waterworld',
    imageURL: '/assets/events/EVENT1716123011161.jpg',
    price: 45000,
    description:
      '"Wahoo Waterworld" adalah sebuah taman air yang terletak di dalam kompleks Ancol Dreamland, Jakarta, Indonesia. Taman air ini merupakan salah satu atraksi utama di Ancol yang menawarkan pengalaman bermain air yang seru dan menyegarkan bagi pengunjung dari berbagai usia.',
    availableSeats: 80,
    maxCapacity: 100,
    limitCheckout: 4,
    startDate: '2024-07-02T20:20:53.412Z',
    endDate: '2024-07-04T23:40:53.412Z',
    userId: 2,
    locationId: 265,
    categoryId: 6,
  },
  {
    name: 'Pelatihan Kader Pemuda Bela Negara 2024 Angkatan 2',
    imageURL: '/assets/events/EVENT1716123011156.jpg',
    price: 0,
    description:
      'Kesadaran bela negara itu hakikatnya adalah kesediaan berbakti pada negara dan kesediaan berkorban membela negara. Tercakup di dalamnya adalah bersikap dan berbuat yang terbaik bagi bangsa dan negara. Wujud bela negara ialah cinta tanah air, kesadaran berbangsa dan bernegara, yakin akan kesaktian Pancasila, rela berkorban untuk bangsa dan negara, serta mempunyai kemampuan awal bela negara.',
    availableSeats: 60,
    maxCapacity: 100,
    limitCheckout: 4,
    startDate: '2024-06-28T14:00:53.412Z',
    endDate: '2024-06-30T17:20:53.412Z',
    userId: 2,
    locationId: 265,
    categoryId: 4,
  },
  {
    name: 'Godzilla x Kong: The New Empire',
    imageURL: '/assets/events/EVENT1716123011148.jpg',
    price: 35000,
    description:
      'In "Godzilla x Kong: The New Empire," the world is thrown into chaos as two titans clash in an epic battle for dominance. With humanity caught in the crossfire, the fate of the planet hangs in the balance as Godzilla and Kong, the last of their kind, wage war against each other.',
    availableSeats: 150,
    maxCapacity: 250,
    limitCheckout: 7,
    startDate: '2024-07-06T19:30:53.412Z',
    endDate: '2024-07-08T22:50:53.412Z',
    userId: 10,
    locationId: 265,
    categoryId: 5,
  },
  {
    name: 'We The Fest 2024: Where Music, Arts, and Culture Collide',
    imageURL: '/assets/events/EVENT1716123011133.webp',
    price: 500000,
    description:
      'Get ready for an unforgettable weekend at We The Fest 2024, Indonesias premier music, arts, and culture festival! Held at the iconic JIEXPO Kemayoran in Jakarta, We The Fest promises three days of non-stop entertainment, creativity, and community spirit.',
    availableSeats: 80,
    maxCapacity: 100,
    limitCheckout: 5,
    startDate: '2024-06-23T12:50:53.412Z',
    endDate: '2024-06-25T16:10:53.412Z',
    userId: 4,
    locationId: 364,
    categoryId: 1,
  },
  {
    name: 'MAN WITH A MISSION JAKARTA TOUR 2024',
    imageURL: '/assets/events/EVENT1716123011126.webp',
    price: 400000,
    description:
      'Band dengan konsep unik memakai topeng serigala ini menggabungkan berbagai genre musik. Lagu-lagu seperti "Emotions", "Seven Deadly Sins", dan "Raise your flag" selalu menjadi favorit di konser. Masing-masing band ini memiliki gaya dan daya tarik unik yang bisa menambah variasi dan keunikan pada rangkaian acara konser Anda.',
    availableSeats: 60,
    maxCapacity: 100,
    limitCheckout: 4,
    startDate: '2024-06-30T17:00:53.412Z',
    endDate: '2024-07-02T20:20:53.412Z',
    userId: 10,
    locationId: 364,
    categoryId: 2,
  },
  {
    name: 'El Clásico: FC Barcelona vs Real Madrid',
    imageURL: '/assets/events/EVENT1716123011140.jpg',
    price: 400000,
    description:
      'Get ready for the most anticipated fixture in Spanish football as FC Barcelona and Real Madrid face off in the legendary El Clásico. This clash between the two Spanish giants is not just a game; it`s a battle for supremacy, bragging rights, and the passion of millions of football fans around the world.',
    availableSeats: 70,
    maxCapacity: 100,
    limitCheckout: 5,
    startDate: '2024-06-29T10:30:53.412Z',
    endDate: '2024-07-01T13:50:53.412Z',
    userId: 4,
    locationId: 364,
    categoryId: 3,
  },
  {
    name: 'Pelatihan Public Speaking untuk Pemuda',
    imageURL: '/assets/events/EVENT1716123011155.jpeg',
    price: 0,
    description:
      'Elemen manusia adalah yang terpenting karena manusia merupakan hal yang mendominasi atau bahkan penyebab dari perubahan zaman ini. Manusia yang berkualitas yang tentu saja akan mampu membawa perubahan kearah yang lebih baik, minimal untuk dirinya sendiri. Kualitas manusia dapat dilihat dari berbagai aspek, seperti dilihat dari tingkah laku, cara berfikir, dan tentu saja dilihat dari apa yang dia ucapkan. Kemampuan verbal seseorang menjadi sangat penting karena dengan berbicara orang lain akan mengetahui kemampuan seseorang dan dapat menilainya atau dikenal dengan istilah “Public Speaking”. Terutama untuk seseorang yang memiliki pekerjaan berhubungan langsung dengan customer seperti marketing dan untuk mahasiswa karena dengan mempelajari teknik public speaking dia akan mampu mengemukakan ide-ide brilian yang dapat mengubah keadaan karena pada hakekatnya mahasiswa adalah agent of change.',
    availableSeats: 80,
    maxCapacity: 100,
    limitCheckout: 5,
    startDate: '2024-07-04T19:00:53.412Z',
    endDate: '2024-07-06T22:20:53.412Z',
    userId: 8,
    locationId: 364,
    categoryId: 4,
  },
  {
    name: 'HOW TO MAKE MILLIONS BEFORE GRANDMA DIES',
    imageURL: '/assets/events/EVENT1716123011147.jpeg',
    price: 45000,
    description:
      'A man quits work to care for dying grandmother, motivated by her fortune. He schemes to win her favor before she passes.',
    availableSeats: 60,
    maxCapacity: 100,
    limitCheckout: 4,
    startDate: '2024-06-25T13:10:53.412Z',
    endDate: '2024-06-27T16:30:53.412Z',
    userId: 4,
    locationId: 364,
    categoryId: 5,
  },
  {
    name: 'Taman Impian Jaya Ancol',
    imageURL: '/assets/events/EVENT1716123011160.jpg',
    price: 45000,
    description:
      'Di Ancol, pengunjung dapat menemukan berbagai wahana dan atraksi yang menarik, mulai dari taman hiburan, pantai buatan, waterpark, hingga kebun binatang. Salah satu daya tarik utamanya adalah Dunia Fantasi (Dufan), taman hiburan yang menawarkan berbagai wahana seru seperti roller coaster, permainan air, dan atraksi interaktif lainnya yang cocok untuk keluarga dan anak-anak.',
    availableSeats: 100,
    maxCapacity: 100,
    limitCheckout: 6,
    startDate: '2024-06-20T19:30:53.412Z',
    endDate: '2024-06-22T22:50:53.412Z',
    userId: 4,
    locationId: 364,
    categoryId: 6,
  },
  {
    name: 'MAROON 5 : Adam Levine Solo 2024',
    imageURL: '/assets/events/EVENT1716123011125.jpg',
    price: 350000,
    description:
      'Dengan vokal khas Adam Levine, Maroon 5 telah menghasilkan banyak hits seperti "Sugar", "Girls Like You", dan "Moves Like Jagger". Konser mereka selalu penuh dengan energi dan hiburan.',
    availableSeats: 120,
    maxCapacity: 250,
    limitCheckout: 7,
    startDate: '2024-06-23T18:00:53.412Z',
    endDate: '2024-06-25T21:20:53.412Z',
    userId: 4,
    locationId: 364,
    categoryId: 2,
  },
  {
    name: 'Saranghaeyo Indonesia 2024: A Celebration of Korean Culture and Entertainment',
    imageURL: '/assets/events/EVENT1716123011132.webp',
    price: 400000,
    description:
      'Get ready for an enchanting journey into the heart of Korean culture at Saranghaeyo Indonesia 2024! This two-day extravaganza promises to immerse attendees in the vibrant world of K-pop, K-drama, cuisine, fashion, and more. Hosted at the prestigious Jakarta Convention Center, Saranghaeyo Indonesia is the ultimate destination for fans of Korean entertainment and enthusiasts of Korean culture.',
    availableSeats: 80,
    maxCapacity: 200,
    limitCheckout: 5,
    startDate: '2024-07-09T15:40:53.412Z',
    endDate: '2024-07-11T19:00:53.412Z',
    userId: 8,
    locationId: 283,
    categoryId: 1,
  },
  {
    name: 'Barcelona vs Bayern Munich: A Clash of European Titans',
    imageURL: '/assets/events/EVENT1716123011139.jpg',
    price: 400000,
    description:
      'Get ready for a showdown of epic proportions as two European football giants, Barcelona and Bayern Munich, go head-to-head in a highly anticipated UEFA Champions League fixture. This match is not just a game; it`s a clash of titans, a battle for supremacy that will captivate football fans around the world.',
    availableSeats: 50,
    maxCapacity: 90,
    limitCheckout: 4,
    startDate: '2024-07-07T17:00:53.412Z',
    endDate: '2024-07-09T20:20:53.412Z',
    userId: 8,
    locationId: 283,
    categoryId: 3,
  },
  {
    name: 'Siksa Kubur',
    imageURL: '/assets/events/EVENT1716123011146.png',
    price: 450000,
    description:
      'Prepare to be gripped by terror as "Siksa Kubur" takes you on a harrowing journey into the depths of horror. This spine-chilling film event promises to immerse viewers in a world of darkness, suspense, and supernatural dread that will leave you on the edge of your seat until the very end.',
    availableSeats: 150,
    maxCapacity: 250,
    limitCheckout: 7,
    startDate: '2024-07-03T18:30:53.412Z',
    endDate: '2024-07-05T21:50:53.412Z',
    userId: 10,
    locationId: 283,
    categoryId: 5,
  },
  {
    name: 'Seminar Pasar Modal: “Investasi Saham, Lagi Pandemi Begini?”',
    imageURL: '/assets/events/EVENT1716123011154.jpg',
    price: 0,
    description:
      'This seminar will discuss, among others, the opportunities and risks of investing and how to respond to “pom-poms” and “ghosting” in the stock market. Let’s beware and understand more about these new trends.',
    availableSeats: 80,
    maxCapacity: 150,
    limitCheckout: 5,
    startDate: '2024-06-22T13:50:53.412Z',
    endDate: '2024-06-24T17:10:53.412Z',
    userId: 2,
    locationId: 283,
    categoryId: 4,
  },
  {
    name: 'Coldplay! : A Head Full of Dreams Tour 2024',
    imageURL: '/assets/events/EVENT1716123011124.jpg',
    price: 350000,
    description:
      'Bersiaplah untuk malam yang penuh magis dan emosi bersama Coldplay! Band legendaris asal Inggris ini akan kembali mengunjungi Jakarta dalam rangkaian tur dunia mereka yang bertajuk "Music of the Spheres World Tour 2024". Dengan reputasi yang tak tertandingi dalam menyajikan pertunjukan live yang spektakuler, Coldplay akan membawa penggemarnya dalam perjalanan musikal yang luar biasa.',
    availableSeats: 120,
    maxCapacity: 200,
    limitCheckout: 6,
    startDate: '2024-07-12T17:50:53.412Z',
    endDate: '2024-07-14T21:10:53.412Z',
    userId: 2,
    locationId: 283,
    categoryId: 2,
  },
  {
    name: 'BMTH : I PREVAIL INDONESIA 2024',
    imageURL: '/assets/events/EVENT1716123011123.jpg',
    price: 1000000,
    description:
      'Bring Me The Horizon, yang digawangi oleh Oliver Sykes (vokal), Lee Malia (gitar), Matt Kean (bass), Matt Nicholls (drum), dan Jordan Fish (kibor), dikenal dengan evolusi musik mereka yang dinamis dan eksperimental. Dari suara metalcore yang keras hingga elemen elektronik yang inovatif, BMTH selalu menghadirkan pertunjukan yang energik dan penuh kejutan. Lagu-lagu hits seperti "Can You Feel My Heart", "Drown", "MANTRA", dan "Sleepwalking" akan membuat malam ini tak terlupakan.',
    availableSeats: 50,
    maxCapacity: 200,
    limitCheckout: 5,
    startDate: '2024-07-01T09:00:00',
    endDate: '2024-07-01T10:30:00',
    userId: 4,
    locationId: 283,
    categoryId: 2,
  },
  {
    name: 'Prambanan Jazz Festival 2024: Where Jazz Meets Heritage',
    imageURL: '/assets/events/EVENT1716123011131.jpg',
    price: 100000,
    description:
      'Sambutlah gemerlap lampu dan irama memikat di Prambanan Jazz Festival 2024, festival musik tahunan yang menggabungkan keindahan alam dan warisan budaya dengan magisnya jazz. Terletak di bawah bayangan megah Candi Prambanan yang kuno, festival ini menjanjikan pengalaman tak terlupakan bagi para pecinta musik jazz dari seluruh Indonesia dan dunia.',
    availableSeats: 30,
    maxCapacity: 50,
    limitCheckout: 3,
    startDate: '2024-07-05T14:00:00',
    endDate: '2024-07-05T17:00:00',
    userId: 2,
    locationId: 283,
    categoryId: 1,
  },
  {
    name: 'Manchester United vs Manchester City: The Manchester Derby',
    imageURL: '/assets/events/EVENT1716123011138.jpg',
    price: 150000,
    description:
      'Prepare for one of the most highly anticipated fixtures in English football as Manchester United and Manchester City face off in the intense rivalry known as the Manchester Derby. This clash between the two Manchester giants is not just a game; its a battle for local pride and supremacy in the English Premier League.',
    availableSeats: 20,
    maxCapacity: 50,
    limitCheckout: 2,
    startDate: '2024-07-10T11:00:00',
    endDate: '2024-07-10T14:00:00',
    userId: 8,
    locationId: 165,
    categoryId: 3,
  },
  {
    name: 'AGAK LAEN',
    imageURL: '/assets/events/EVENT1716123011145.jpg',
    price: 20000,
    description:
      'In pursuit of their dream of changing their fate, four friends who guard a haunted house at a night market look for new ways to scare visitors to escape bankruptcy. Unfortunately, Bene, Jegel, Boris and Oki`s efforts resulted in the death of one of their visitors. Panicking, they buried the victim in a haunted house. Unexpectedly, the victim`s spirit wanders around, making the haunted house scary and busy with visitors. When the police started investigating, they were forced to carry out various ridiculous conspiracies to cover up the real incident. What will happen to them next?',
    availableSeats: 15,
    maxCapacity: 20,
    limitCheckout: 2,
    startDate: '2024-07-15T18:00:00',
    endDate: '2024-07-15T20:00:00',
    userId: 10,
    locationId: 165,
    categoryId: 5,
  },
  {
    name: 'Workshop IGA 2024, Tingkatkan Kemampuan Mengelola Reputasi',
    imageURL: '/assets/events/EVENT1716123011153.png',
    price: 15000,
    description:
      'Perhelatan puncak acara The 1st Indonesia GPR Awards (IGA) 2024 yang akan berlangsung di Kota Makassar, 14 - 16 Juni 2023, akan diwarnai dengan workshop. Kegiatan ini dibagi ke dalam dua kelas. Kelas pertama mengangkat tema “Mengelola Persepsi Publik, Menggapai Reputasi Organisasi”. Sementara kelas kedua mengusung topik “Merawat Harmoni Memitigasi Krisis”.  ',
    availableSeats: 25,
    maxCapacity: 200,
    limitCheckout: 3,
    startDate: '2024-07-20T10:00:00',
    endDate: '2024-07-20T13:00:00',
    userId: 4,
    locationId: 165,
    categoryId: 4,
  },
  {
    name: 'Sea World',
    imageURL: '/assets/events/EVENT1716123011159.jpg',
    price: 20000,
    description:
      'Sea World adalah sebuah taman hiburan dan akuarium yang terletak di berbagai lokasi di seluruh dunia, termasuk di Amerika Serikat, Australia, dan Jepang. Taman ini terkenal karena menampilkan atraksi dan pertunjukan hewan laut yang menarik, serta menyediakan pengalaman interaktif yang edukatif bagi pengunjung dari berbagai usia.',
    availableSeats: 40,
    maxCapacity: 200,
    limitCheckout: 4,
    startDate: '2024-07-25T07:30:00',
    endDate: '2024-07-25T09:30:00',
    userId: 8,
    locationId: 165,
    categoryId: 6,
  },
  {
    name: 'ONE OK ROCK Live in Concert 2024',
    imageURL: '/assets/events/EVENT1716123011121.jpg',
    price: 100000,
    description:
      'Bersiaplah untuk malam yang penuh energi dan tak terlupakan bersama ONE OK ROCK! Band rock legendaris asal Jepang ini akan mengguncang Jakarta dengan penampilan live yang spektakuler. Setelah sukses dengan tur dunia mereka sebelumnya, ONE OK ROCK kembali ke Indonesia dengan membawa musik yang menginspirasi dan penampilan yang memukau.',
    availableSeats: 30,
    maxCapacity: 50,
    limitCheckout: 3,
    startDate: '2024-07-30T14:00:00',
    endDate: '2024-07-30T16:00:00',
    userId: 2,
    locationId: 165,
    categoryId: 2,
  },
  {
    name: 'Lalala Fest 2024',
    imageURL: '/assets/events/EVENT1716123011130.webp',
    price: 200000,
    description:
      'Selamat datang di Lalala Fest 2024, festival musik tahunan yang menghadirkan pengalaman tak terlupakan bagi para pecinta musik, seni, dan komunitas. Dipersembahkan dengan bangga oleh para penggiat budaya lokal dan internasional, Lalala Fest menjanjikan tiga hari yang penuh warna, suara, dan kegembiraan di tengah hiruk pikuk kota Jakarta.',
    availableSeats: 20,
    maxCapacity: 30,
    limitCheckout: 2,
    startDate: '2024-08-05T19:00:00',
    endDate: '2024-08-05T21:00:00',
    userId: 10,
    locationId: 165,
    categoryId: 1,
  },
  {
    name: 'AC Milan vs Juventus: Clash of Titans',
    imageURL: '/assets/events/EVENT1716123011137.png',
    price: 0,
    description:
      'Get ready for an epic showdown as two Italian football giants, AC Milan and Juventus, go head-to-head in a highly anticipated Serie A match at the iconic San Siro Stadium. This fixture is not just a game; its a clash of titans, a battle for supremacy that will captivate football fans around the world.',
    availableSeats: 15,
    maxCapacity: 200,
    limitCheckout: 2,
    startDate: '2024-08-10T11:00:00',
    endDate: '2024-08-10T13:00:00',
    userId: 4,
    locationId: 165,
    categoryId: 3,
  },
  {
    name: 'Haikyuu 2024: The Next Spike',
    imageURL: '/assets/events/EVENT1716123011144.jpg',
    price: 20000,
    description:
      'Calling all Haikyuu fans! Get ready for an exciting virtual event celebrating the beloved sports anime and manga series. Haikyuu 2024 brings together fans from around the world to commemorate the journey of Karasuno High School and other volleyball teams as they strive for greatness on and off the court.',
    availableSeats: 30,
    maxCapacity: 50,
    limitCheckout: 3,
    startDate: '2024-08-15T18:30:00',
    endDate: '2024-08-15T21:30:00',
    userId: 8,
    locationId: 162,
    categoryId: 5,
  },
  {
    name: 'IWSER 2022: Workshop Series Indonesia Berkarya',
    imageURL: '/assets/events/EVENT1716123011152.jpg',
    price: 200000,
    description:
      'Workshop Series Indonesia Berkarya merupakan serangkaian acara dari The 2nd International Webinar Series Educational Revolution (IWSER) 2022. Terdapat 4 sesi dalam workshop ini yang disampaikan oleh 6 narasumber yang ahli dalam bidangnya. Workshop ini akan dilaksanakan secara online melalui platform Zoom Meeting serta ditayangkan secara langsung di Youtube Rosevonia Channel.',
    availableSeats: 20,
    maxCapacity: 30,
    limitCheckout: 2,
    startDate: '2024-08-20T14:00:00',
    endDate: '2024-08-20T17:00:00',
    userId: 2,
    locationId: 162,
    categoryId: 4,
  },
];
