export const users = [
  {
    username: 'johndoe',
    email: 'john.doe@example.com',
    password: '1234',
    isAdmin: false,
    referralCode: 'ABCDEF',
  },
  {
    username: 'alice',
    email: 'alice@example.com',
    password: '1234',
    isAdmin: true,
    referralCode: null,
  },
  {
    username: 'bobsmith',
    email: 'bob.smith@example.com',
    password: '1234',
    isAdmin: false,
    referralCode: 'GHIJKL',
  },
  {
    username: 'emily',
    email: 'emily@example.com',
    password: '1234',
    isAdmin: true,
    referralCode: null,
  },
  {
    username: 'sam',
    email: 'sam@example.com',
    password: '1234',
    isAdmin: false,
    referralCode: 'MNOPQR',
  },
  {
    username: 'davidbrown',
    email: 'david.brown@example.com',
    password: '1234',
    isAdmin: false,
    referralCode: 'STUVWX',
  },
  {
    username: 'laurasmith',
    email: 'laura.smith@example.com',
    password: '1234',
    isAdmin: false,
    referralCode: 'YZ1234',
  },
  {
    username: 'markjones',
    email: 'mark.jones@example.com',
    password: '1234',
    isAdmin: true,
    referralCode: null,
  },
  {
    username: 'sarah',
    email: 'sarah@example.com',
    password: '1234',
    isAdmin: false,
    referralCode: '567890',
  },
  {
    username: 'michael',
    email: 'michael@example.com',
    password: '1234',
    isAdmin: true,
    referralCode: null,
  },
];
